apiVersion: v1
kind: Template
metadata:
  name: mongodbstatefulset
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: mongodb-internal
    labels:
      name: mongodb
  spec:
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: mongodb
- kind: Service
  apiVersion: v1
  metadata:
    name: mongodb
    labels:
      name: mongodb
  spec:
    ports:
      - name: mongodb
        port: 27017
    selector:
      name: mongodb
- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    name: mongodb
  spec:
    serviceName: mongodb-internal
    replicas: 3
    selector:
      matchLabels:
        name: mongodb
    template:
      metadata:
        labels:
          name: mongodb
      spec:
        containers:
          - name: mongo-container
            image: mongodb-ephemeral
            ports:
              - containerPort: 27017
            args:
              - run-mongod-replication
            volumeMounts:
              - name: mongo-data
                mountPath: /var/lib/mongodb/data
            env:
              - name: MONGODB_DATABASE
                value: "mongodb"
              - name: MONGODB_USER
                value: "mongodb"
              - name: MONGODB_PASSWORD
                value: "mongodb"
              - name: MONGODB_ADMIN_PASSWORD
                value: "mongodb"
              - name: MONGODB_REPLICA_NAME
                value: "rs0"
              - name: MONGODB_KEYFILE_VALUE
                value: "1q2w3e4r5t6y7u8i9o0p"
              - name: MONGODB_SERVICE_NAME
                value: "mongodb-internal"
            readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
              initialDelaySeconds: 20
    volumeClaimTemplates:
      - metadata:
          name: mongo-data
          labels:
            name: mongodb
        spec:
          accessModes: [ ReadWriteOnce ]
          resources:
            requests:
              storage: "4Gi"
