apiVersion: v1
kind: Template
metadata:
  name: nexus
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: nexus3
    name: nexus3
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/sonatype/nexus3:latest
      name: latest
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: nexus-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: nexus3
    name: nexus3
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: nexus3
      deploymentconfig: nexus3
    strategy:
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Recreate
    template:
      metadata:
        labels:
          app: nexus3
          deploymentconfig: nexus3
      spec:
        containers:
        - image: sonatype/nexus3
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nexus3
          ports:
          - containerPort: 8081
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /repository/maven-public/
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 600
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /nexus-data
            name: nexus3-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nexus3-volume-1
          persistentVolumeClaim:
            claimName: nexus-pvc
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nexus3
        from:
          kind: ImageStreamTag
          name: nexus3:latest
          namespace: ${GUID}-nexus
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nexus3
    name: nexus-registry
  spec:
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: nexus3
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: nexus3
    name: nexus3
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: nexus3
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nexus3
    name: nexus-registry
  spec:
    host: nexus-registry-${GUID}-nexus.apps.na39.openshift.opentlc.com
    port:
      targetPort: 5000
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: nexus-registry
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nexus3
    name: nexus3
  spec:
    host: nexus3-${GUID}-nexus.apps.na39.openshift.opentlc.com
    port:
      targetPort: 8081-tcp
    to:
      kind: Service
      name: nexus3
      weight: 100
    wildcardPolicy: None
parameters:  
- description: GUID
  from: '[A-Z0-9]{8}'   
  generate: expression
  name: GUID
