apiVersion: v1
kind: BuildConfig
metadata:
  name: parksmap-pipeline
spec:
  source:
    type: Git
    git:
      uri: https://github.com/xingguang2013/advdev_homework_template.git
      ref: master
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
       env:
         - name: GUID
           value: ${GUID}
         - name: CLUSTER
           value: ${CLUSTER}
       jenkinsfilePath: ParksMap/Jenkinsfile